name: Go Docker Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file go/production.Dockerfile --tag filecan.xyz:5432/fc-go
      - name: Docker Login
        run: docker login filecan.xyz:5432 -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Docker Push
        run: docker push filecan.xyz:5432/fc-go
